version: "3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    networks:
      - network1

networks:
  network1:
    name: car-simulator-kafka_internal-kafka-network
    external: true
